### ISSUE TITLE
Always returns root on initial page load

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz.Router#20]
I noticed that [this page](https://fable.io/blog/Introducing-Feliz-v1.0.html#introducing-feliz-v1-0) has a link to [https://cmeeren.github.io/Feliz.MaterialUI/#ecosystem](https://cmeeren.github.io/Feliz.MaterialUI/#ecosystem), but the latter page only shows the root. (You can't even click "Ecosystem" in the menu - you have to navigate to another page, and then back to Ecosystem.)

[Here is the code that runs the page.](https://github.com/cmeeren/Feliz.MaterialUI/blob/500eada721f1abbc85831314f6e2e6b2552c5e49/docs-app/src/App.fs#L270-L305) Seems correct to me. So is this a bug in Feliz.Router?

**Comment by Zaid-Ajaj** [comment]
Hi @cmeeren, I see the problem but I am not sure from first glance why it happens 😓 I can try to investigate it soon from your docs app

**Comment by Zaid-Ajaj** [comment]
I think I found the problem in [this line](https://github.com/cmeeren/Feliz.MaterialUI/blob/500eada721f1abbc85831314f6e2e6b2552c5e49/docs-app/src/App.fs#L50)

As of recent versions of Feliz.Router, you should provide the initial route in your `init` function like this:
```fs
let init () = {
  CurrentPath = Router.currentUrl()
  CustomThemeMode = None
}
```
This is because the `onUrlChanged` no longer trigger when the router component is mounted on application startup. Instead, the event is only triggered when the url actually changes *after* the router is mounted.

**Comment by cmeeren** [comment]
Excellent, thanks! Works now, published updated docs.
